---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cart-config
data:
  REDIS_HOST: "redis"
  CATALOGUE_HOST: "http://catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: cart
  labels:
    name: cart
    tier: app
spec:
  containers:
  - name: cart
    imagePullPolicy: Always
    image: sahiya/cart:k8
    envFrom:
    - configMapRef:
        name: cart-config   
---
apiVersion: v1
kind: Service
metadata:
  name: cart
spec:
  selector:
    name: cart
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
