apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tire: db
spec:
  containers:
  - name: mongodb
    imagePullPolicy: Always
    image: sahiya/mongodb:v2
    ports:
     - containerPort: 27017
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "128m"  
        memory: "156Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    name: mongodb
    tire: db
  ports:
   - protocol: TCP
     port: 27017
     targetPort: 27017
 

