---
apiVersion: v1
kind: Pod
metadata:
  name: mongodb
  labels:
    name: mongodb
    tier: db
spec:
  containers:
  - name: mongodb
    imagePullPolicy: Always
    image: sahiya/mongodb:v2
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "128m"  
        memory: "156Mi"
    ports:
      - containerPort: 27017
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    name: mongodb
    tier: db
  ports:
   - protocol: TCP
     port: 80
     targetPort: 27017
