---
apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    name: mysql
    tier: db
spec:
  containers:
  - name: mysql
    imagePullPolicy: Always
    image: sahiya/mysql:v2
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "128m"  
        memory: "156Mi"
    ports:
      - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  selector:
    name: mysql
    tier: db
  ports:
   - protocol: TCP
     port: 80
     targetPort: 3306 
