apiVersion: v1
kind: Pod
metadata:
  name: catalogue
  labels:
    name: catalogue
    tire: app
spec:
  containers:
  - name: catalogue
    imagePullPolicy: Always
    image: sahiya/catalogue:v2
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"
      limits:
        cpu: "128m"  
        memory: "156Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-service
spec:
  selector:
    name: catalogue
    tire: app
  ports:
   - protocol: TCP
     port: 8080
     targetPort: 8080
 

