---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:27017/catalogue"
---
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    name: user
    tier: app
spec:
  containers:
  - name: user
    imagePullPolicy: Always
    image: sahiya/user:v2
    envFrom:
    - configMapRef:
        name: user-config
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    name: user
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
