---
apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    name: web
    tier: frontend
spec:
  containers:
  - name: web
    image: sahiya/web:sahiya/web:k8
    ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
  selector:
    name: web
    tier: frontend
  ports:
   - protocol: TCP
     port: 80
     targetPort: 80
  type: LoadBalancer
